import { Theme } from "../theme.slint";

export component IconButton inherits Rectangle {
    in-out property icon <=> icon.source;
    callback clicked <=> touch.clicked;
    in-out property <bool> checked;

    width: 40px;
    height: 40px;
    border-width: touch.has-hover ? 1.5px : 1px;
    border-radius: 12px;
    opacity: touch.pressed ? 0.7 : 1.0;
    border-color: Theme.icon_button_border_color;

    icon:= Image {
        width: 30px;
        height: 30px;
    }

    touch := TouchArea {
        clicked => { root.checked = !root.checked }
    }
}



export component BaseButton inherits Rectangle {
    callback clicked <=> touch.clicked;
    in-out property <bool> checked;

    opacity: touch.pressed ? 0.5 : 0.8;
    width: 120px;
    height: 40px;
    border-radius: Theme.border_radius;
    border-color: Theme.icon_button_border_color;
    background: touch.has-hover ? Theme.hover_color : Theme.primary_color;

    touch := TouchArea {
        clicked => { root.checked = !root.checked }
    }
}
