import { Button, CheckBox, HorizontalBox, VerticalBox } from "std-widgets.slint";
import { AppConfig } from "../global.slint";
import { Theme } from "../theme.slint";

export component CollectionComponent inherits Rectangle {
    in property <string> name;
    in property <string> id;

    height: 40px;
    border-radius: Theme.border_radius;
    touch-area := TouchArea {}
    border-color: touch-area.has-hover ? Theme.primary_color : self.background;
    border-width: Theme.hover_border_width;

    HorizontalLayout {
        alignment: space-between;
        padding-top: 5px;
        padding-bottom: 5px;
        padding-left: 10px;
        padding-right: 10px;
        spacing: 10px;


        Rectangle {
            width: Theme.icon_box_with;
            height: Theme.icon_box_with;
            background: touch.has-hover ? Theme.hover_color : root.background;
            border-radius: Theme.border_radius;

            touch := TouchArea{
                mouse-cursor: self.has-hover ? pointer : default;
                clicked => {
                    AppConfig.get_icons();
                    AppConfig.show_icons_popup = true;
                }
            }

            folder := Image {
                source: @image-url("../icons/folder.svg");
                padding-right: 10px;
                colorize: Theme.icon_color;
            }
        }

        Text {
            vertical-alignment: center;
            text: name;
            font-size: Theme.label_font_size_medium_small;
            color: Theme.label_text_color;
        }


        Rectangle {
            width: Theme.icon_box_with;
            height: Theme.icon_box_with;
            background: more_touch.has-hover ? Theme.hover_color : root.background;
            border-radius: Theme.border_radius;

            more_touch := TouchArea{
                mouse-cursor: self.has-hover ? pointer : default;
            }
            more := Image {
                source: @image-url("../icons/more.svg");
                colorize: Theme.icon_color;
            }
        }
        
    }
}    