import { Theme } from "../theme.slint";
import {SearchForm} from "./forms.slint";


export component CollectionSection inherits Rectangle {
    border-color: Theme.border_color;
    vertical-stretch: 1;
    border-width: Theme.border_width;
    
    VerticalLayout { 
        
        padding-bottom: 5px;
        padding-top: 45px;
        padding-left: 2px;
        padding-right: 3px + Theme.border_width;

        Text {
            text: "Collections ";
            font-size: Theme.label_font_size_medium;
            color: Theme.label_text_color;
            horizontal-alignment: center;
            vertical-stretch: 1;
        }
        
        SearchForm {
        }
    }
}