
import { Theme } from "../theme.slint";
import { AppConfig, CollectionItemActive } from "../global.slint";

import { GridView } from "./gridview.slint";
import { ScrollView } from "std-widgets.slint";


export component CollectionsDropDown inherits Rectangle {
    width: 200px;
    background: Theme.app_background_color.darker(20%);
    border-radius: Theme.border_radius;
    visible: AppConfig.show_collection_more_dropdown;
    height: delete.height + add_http.height + 10px;
    x: AppConfig.active_collection_item.x;
    y: AppConfig.active_collection_item.y + 30px;
    z: 101;


    VerticalLayout {
        delete := Rectangle {
            border-radius: Theme.border_radius;
            padding-left: 5px;
            padding-right: 5px;
            height: 40px;
            background: touch.has-hover ? Theme.hover_color : root.background;

            touch := TouchArea{
                mouse-cursor: self.has-hover ? pointer : default;
                clicked => {}
            }

            HorizontalLayout {
                horizontal-stretch: 1;
                alignment: start;
                spacing: 15px;
                
    
                Image {
                    vertical-alignment: center;
                    source: @image-url("../icons/delete.svg");
                    colorize: Theme.icon_color;
                }
                Text {
                    vertical-alignment: center;
                    text: "Delete Collection";
                    color: Theme.label_text_color;
                    font-size: Theme.label_font_size_medium_small;
                }
            }
        }

        add_http := Rectangle {
            border-radius: Theme.border_radius;
            padding-left: 5px;
            padding-right: 5px;
            height: 40px;
            background: touch_2.has-hover ? Theme.hover_color : root.background;

            touch_2 := TouchArea{
                mouse-cursor: self.has-hover ? pointer : default;
                clicked => {
                    debug(AppConfig.window_width, AppConfig.window_height)
                }
            }

            HorizontalLayout {
                horizontal-stretch: 1;
                alignment: start;
                spacing: 15px;
    
                Image {
                    vertical-alignment: center;
                    source: @image-url("../icons/http.svg");
                    colorize: Theme.icon_color;
                }
                Text {
                    vertical-alignment: center;
                    text: "Add http Request";
                    color: Theme.label_text_color;
                    font-size: Theme.label_font_size_medium_small;
                }
            }
        }
        
    }

}