import { Theme } from "../theme.slint";
import {SearchForm} from "./forms.slint";
import { IconButton } from "./buttons.slint";
import { AppConfig, CollectionItem} from "../global.slint";
import { CollectionComponent } from "./collection_item.slint";


export component CollectionSection inherits Rectangle {
    border-color: Theme.border_color;
    vertical-stretch: 1;
    border-width: Theme.border_width;
    in-out property <[CollectionItem]> collection_items: AppConfig.collection_items;

    VerticalLayout { 
        padding-bottom: 8px;
        padding-top: 8px;
        padding-left: 5px;
        padding-right: 5px;

        HorizontalLayout {
            horizontal-stretch: 1;
            alignment: end;
            padding-right: 5px;

            image := Image {
                source: @image-url("../icons/create_folder.svg");
                width: touch.pressed ? Theme.icon_width_pressed : Theme.icon_width;
                opacity: touch.has-hover ? Theme.icon_opacity_hover : Theme.icon_opacity;
                colorize: Theme.icon_button_image_overlay_color;
                
                touch := TouchArea {
                    clicked => {
                        AppConfig.create_collection();
                    }
                }
            }
        }

        VerticalLayout {
            vertical-stretch: 1;
            for list-item[i] in collection_items: CollectionComponent {
                name: list-item.name;
                id: list-item.id;
            }
        }
        
        SearchForm {
        }
    }
}