import { ListView } from "std-widgets.slint";

import { Button, CheckBox, HorizontalBox, VerticalBox } from "std-widgets.slint";
import { AppConfig, CollectionItemActive } from "../global.slint";
import { Theme } from "../theme.slint";
import { RequestComponent } from "./request_item.slint";


export component CollectionComponent inherits Rectangle {
    in property <string> name;
    in property <string> id;
    in property <color> component_background;
    in property <image> icon;
    in property <int> index;
    in property <string> icon_name;
    in-out property <int> request_count;
    height: (AppConfig.show_active_collection_requests == true && AppConfig.active_collection_item.id == id && AppConfig.active_collection_requests.length > 0) ? 350px : 50px;

    touch-area := TouchArea {
        property<length> position_x;
        property<length> position_y;
        clicked => {
            position_x = root.x + root.width;
            position_y = (index * root.height) + AppConfig.collections_viewport_y;
            AppConfig.active_collection_item = {
                id: id,
                name: name,
                index: index,
                x: position_x,
                y: position_y
            };
            AppConfig.show_collection_more_dropdown = false;
            AppConfig.show_active_collection_requests = !AppConfig.show_active_collection_requests;

            if AppConfig.show_active_collection_requests == true {
                AppConfig.get_requests(id);

            } else {
                AppConfig.active_collection_requests = [];
            }
        }
    }

    background: touch-area.has-hover ? component_background.darker(20%) : AppConfig.active_collection_item.id == id ? component_background.darker(20%) : component_background;
    border-width: Theme.hover_border_width;

    VerticalLayout {
        HorizontalLayout {
            padding-top: 5px;
            padding-bottom: 5px;
            padding-left: 10px;
            padding-right: 10px;
            spacing: 10px;

            VerticalLayout {
                alignment: center;
                padding-right: 10px;
                Rectangle {
                    width: Theme.icon_box_with;
                    height: Theme.icon_box_with;
                    background: touch.has-hover ? Theme.hover_color : root.background;
                    border-radius: Theme.border_radius;

                    touch := TouchArea{
                        mouse-cursor: self.has-hover ? pointer : default;
                        clicked => {
                            AppConfig.active_collection_item = {
                                id: id,
                                name: name,
                                index: index,
                                x: root.x + root.width,
                                y: root.y + root.height
                            };
                            AppConfig.get_requests(id);
                            AppConfig.show_icons_popup = !AppConfig.show_icons_popup;
                        }
                    }

                    Image {
                        source: icon;
                        width: Theme.icon_box_with - 2px;
                        height: Theme.icon_box_with - 2px;
                    }
                }
            }


            if AppConfig.active_collection_rename_mode == true && AppConfig.active_collection_item.id == id :
                text_input := TextInput {
                    color: Theme.label_text_color;
                    vertical-alignment: center;
                    wrap: no-wrap;
                    single-line: true;
                    text: name;
                    font-size: Theme.label_font_size_medium_small;
                    accepted() => {
                        if self.text != "" {
                            AppConfig.update_collection(id, self.text, icon_name, index);
                        }
                        AppConfig.active_collection_rename_mode = false;
                    }

                    init => {
                        // Give focus to text box
                        self.focus();
                        self.select-all();
                    }

                }


            // Conditionally display the Text
            if !(AppConfig.active_collection_rename_mode == true && AppConfig.active_collection_item.id == id) :

                VerticalLayout {
                    text := Text {
                        vertical-alignment: center;
                        text: name;
                        font-size: Theme.label_font_size_medium_small;
                        color: Theme.label_text_color;

                        max-width: 200px;
                        wrap: TextWrap.no-wrap;
                        overflow: TextOverflow.elide;
                    }

                    Text {
                        text: "\{request_count} requests";
                        font-size: Theme.label_font_size_small;
                        color: Theme.label_text_color;
                        opacity: 0.4;

                        vertical-alignment: center;
                        wrap: TextWrap.no-wrap;
                        overflow: TextOverflow.elide;
                    }
                        
                }

            
            Rectangle {horizontal-stretch: 1;}
            VerticalLayout {
                alignment: center;

                more_btn := Rectangle {
                    width: Theme.icon_box_with;
                    height: Theme.icon_box_with;
                    background: more_touch.has-hover ? Theme.hover_color : root.background;
                    border-radius: Theme.border_radius;

                    more_touch := TouchArea{
                        mouse-cursor: self.has-hover ? pointer : default;
                        property<length> position_x;
                        property<length> position_y;

                        clicked => {
                            AppConfig.get_requests(id);
            
                            if AppConfig.show_active_collection_requests == true {
                                AppConfig.active_collection_item = {
                                    id: id,
                                    name: name,
                                    index: index,
                                    x: position_x,
                                    y: position_y
                                };
                                AppConfig.show_active_collection_requests = false;
                            }
                            else {
                                position_x = root.x + root.width;
                                position_y = (index * root.height) + AppConfig.collections_viewport_y;

                                AppConfig.active_collection_item = {
                                    id: id,
                                    name: name,
                                    index: index,
                                    x: position_x,
                                    y: position_y
                                };
                                AppConfig.show_collection_more_dropdown = !AppConfig.show_collection_more_dropdown;
                            }
                            
                        }
                    }
                    more := Image {
                        source: @image-url("../icons/more.svg");
                        colorize: Theme.icon_color;
                    }
                }
            }
        }

        if AppConfig.show_active_collection_requests == true && AppConfig.active_collection_item.id == id && AppConfig.active_collection_requests.length > 0:
            HorizontalLayout {
                padding-right: 40px;
                padding-left: 30px;

                ListView {
                    height: 300px;
            
                    for list_item[i] in AppConfig.active_collection_requests: RequestComponent {
                        id: list_item.id;
                        name: list_item.name;
                        url: list_item.url;
                        protocol: list_item.protocol;
                        http_method: list_item.http_method;
                        background: root.background;
                        index: i;
                        collection_index: root.index;
                    }

                    changed viewport-y => {
                        AppConfig.requests_viewport_y = self.viewport-y;
                    }
                
                }
            }
        
        

    }
}