import { Theme } from "../theme.slint";

export component SearchForm inherits Rectangle {
    border-radius: Theme.border_radius;
    border-color: Theme.border_color;
    border-width: Theme.border_width;
    height: text.height;
    background: red;
 
    HorizontalLayout {
        spacing: 10px;
        padding-left: 3px;
        padding-top: 3px;

        image := Image {
            source: @image-url("../icons/search.svg");
            opacity: Theme.text_opacity;
            vertical-alignment: center;
        }
        
        text := TextInput {
            height: 30px;
            text: "Filter";
            color: Theme.label_text_color;
            horizontal-stretch: 1;
            vertical-alignment: center;
            opacity: Theme.text_opacity;
            font-size: Theme.label_font_size_small;
            wrap: no-wrap;
            single-line: true;

            edited() => {
                debug("With", text.width);
                if (text.width - image.width > root.width) {
                    text.read-only = true;
                } else {
                    text.read-only = false;
                }
            }
        }
    }
    
}