import { ScrollView} from "std-widgets.slint";

export component GridView inherits ScrollView {
    horizontal-stretch: 1;
    vertical-stretch: 1;
    viewport-height: 200px; // to be set from outside like Math.round(your_model.length / columns) * preferredCellHeight;
    viewport-width: 1000px; // to be set from outside as this.parent.width;

    in property <int> columns: (self.width / 1px) / self.preferred_cell_height;
    in property <int> preferred_cell_height: 50;
    in property <int> expected_width: (self.width / 1px) / columns;
}