import { ScrollView, HorizontalBox} from "std-widgets.slint";

import { Theme } from "../theme.slint";

// Define your individual rectangle widget
component HeaderItem inherits Rectangle {
    width: 150px;
    height: 100%; // Take full height of the parent (ScrollView viewport)
    background: red; // Just for visualization, change this
    // Add any other properties or content you want for each item
    Text {
        text: "Item";
        color: white;
        horizontal-alignment: center;
        vertical-alignment: center;
    }
}

export component HeadersSection inherits Rectangle {
    padding: 20px;
    border-color: Theme.border_color;
    horizontal-stretch: 1;
    border-width: Theme.border_width;
    height: 50px;
    width: 100%;

    TouchArea {
        clicked => {
            root.focus()
        }
    }

    forward-focus: my-key-handler;
    my-key-handler := FocusScope {
        key-pressed(event) => {

            if (event.text == Key.LeftArrow) {
                scroll.viewport-x -= 30px;
                checkScrollEdges()
            }
            if (event.text == Key.RightArrow) {
                scroll.viewport-x += 30px;
                checkScrollEdges()
            } 
            accept
        }
    }

    property <length> min_scroll_x;
    function checkScrollEdges() {
        min_scroll_x = scroll.visible-width - scroll.viewport-width;
    
        if (scroll.viewport-x >= 0) {
            scroll.viewport-x = 0px;
        }

        if (scroll.viewport-x <= min_scroll_x) {
            scroll.viewport-x = min_scroll_x;
        }
    }

    scroll := ScrollView {
        horizontal-scrollbar-policy: always-off;
        content_box := HorizontalBox {
            spacing: 10px;
            height: 100%;

            HeaderItem { background: #FF5733; }
            HeaderItem { background: #33FF57; }
            HeaderItem { background: #3357FF; }
            HeaderItem { background: #F333FF; }
            HeaderItem { background: #FFFF33; }
            HeaderItem { background: #33FFFF; }
            HeaderItem { background: #8A2BE2; }
            HeaderItem { background: #008080; }
            HeaderItem { background: #FF4500; }
            HeaderItem { background: #228B22; }
            HeaderItem { background: #8B0000; }
        }
    }
}
