import { BaseButton } from "../components/buttons.slint";
import { Theme } from "../theme.slint";
import { VerticalBox, HorizontalBox } from "std-widgets.slint";
import { AppLogic } from "../global.slint";


component GetStartedButton inherits BaseButton {
    Text {
        text: "Get started";
        font-size: Theme.label_font_size_small;
        color: Theme.label_text_color;
    }
}



export component LandingPage inherits Rectangle {
    background: Theme.app_background_color;
    padding: 20px;


    VerticalLayout {
        width: 100%;
        height: 100%;
        alignment: center;
        spacing: 20px;
        
        Image {
            source: @image-url("../icons/sun.svg");
            width: 50px;
            height: 50px;
            x: (parent.width - self.width) / 2;
            
        }

        Text {
            text: "Welcome to Querry!";
            font-size: Theme.label_font_size_large;
            color: Theme.label_text_color;
            // x: (parent.width - self.width) / 2;
            horizontal-alignment: center;
        }

        Text {
            text: "Use collections to save your requests and share them with others.";
            font-size: Theme.label_font_size_medium;
            color: Theme.label_text_color;
            horizontal-alignment: center;
        }

        GetStartedButton {
            x: (parent.width - self.width) / 2;
            clicked => { AppLogic.change_page(2); }
        }
    }

    // HorizontalLayout {
    //     width: 100%;
    //     height: 100%;
    //     spacing: 20px;
    //     padding: 20px;
    //     alignment: center;


        
        
    // }

    

}


