
import { Theme } from "../theme.slint";
import { AppConfig, CollectionItemActive } from "../global.slint";


export component RequestsDropDown inherits Rectangle {
    width: 200px;
    background: Theme.app_background_color.darker(20%);
    visible: AppConfig.show_request_more_dropdown;
    height: delete.height + duplicate.height + rename.height;
    x: AppConfig.active_request_item.x;
    y: AppConfig.active_request_item.y;
    z: 101;
    border-radius: Theme.border_radius;

    property <length> items_padding_left: 5px;

    VerticalLayout {
        
        rename := Rectangle {
            border-radius: Theme.border_radius;
            height: 40px;
            background: touch_rename.has-hover ? Theme.hover_color : root.background;

            touch_rename := TouchArea{
                mouse-cursor: self.has-hover ? pointer : default;
                clicked => {
                    AppConfig.active_request_rename_mode = true;
                    AppConfig.show_request_more_dropdown = !AppConfig.show_request_more_dropdown;
                }
            }

            HorizontalLayout {
                horizontal-stretch: 1;
                alignment: start;
                spacing: 15px;
                padding-left: root.items_padding_left;
    
                Image {
                    vertical-alignment: center;
                    source: @image-url("../icons/rename.svg");
                    colorize: Theme.icon_color;
                }
                Text {
                    vertical-alignment: center;
                    text: "Rename";
                    color: Theme.label_text_color;
                    font-size: Theme.label_font_size_medium_small;
                }
            }
        }

        delete := Rectangle {
            height: 40px;
            background: touch.has-hover ? Theme.hover_color : root.background;

            touch := TouchArea{
                mouse-cursor: self.has-hover ? pointer : default;
                clicked => {
                    AppConfig.show_request_more_dropdown = !AppConfig.show_request_more_dropdown;
                    AppConfig.active_request_item = {
                        name: "",
                        id: "",
                        index: -1,
                        x:-1px,
                        y:-1px,
                        collection_index: -1
                    };
                    AppConfig.show_active_collection_requests = false;
                    AppConfig.remove_request_item(AppConfig.active_request_item.id, AppConfig.active_request_item.index, AppConfig.active_request_item.collection_index);
                }
            }

            HorizontalLayout {
                horizontal-stretch: 1;
                alignment: start;
                spacing: 15px;
                padding-left: root.items_padding_left;
                
    
                Image {
                    vertical-alignment: center;
                    source: @image-url("../icons/delete.svg");
                    colorize: Theme.icon_color;
                }
                Text {
                    vertical-alignment: center;
                    text: "Delete";
                    color: Theme.label_text_color;
                    font-size: Theme.label_font_size_medium_small;
                }
            }
        }

        duplicate := Rectangle {
            height: 40px;
            border-radius: Theme.border_radius;
            background: touch_dub.has-hover ? Theme.hover_color : root.background;

            touch_dub := TouchArea{
                mouse-cursor: self.has-hover ? pointer : default;
                clicked => {
                    debug(AppConfig.window_width, AppConfig.window_height)
                }
            }

            HorizontalLayout {
                horizontal-stretch: 1;
                alignment: start;
                spacing: 15px;
                padding-left: root.items_padding_left;
    
                Image {
                    vertical-alignment: center;
                    source: @image-url("../icons/duplicate.svg");
                    colorize: Theme.icon_color;
                }
                Text {
                    vertical-alignment: center;
                    text: "Duplicate";
                    color: Theme.label_text_color;
                    font-size: Theme.label_font_size_medium_small;
                }
            }
        }
        
    }

}