//! `SeaORM` Entity. Generated by sea-orm-codegen 0.12.10

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "collection")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: String,
    pub name: String,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::collection_header::Entity")]
    CollectionHeader,
}

impl Related<super::collection_header::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::CollectionHeader.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
