import { Button, VerticalBox } from "std-widgets.slint";
import { LandingPage } from "./landing_page.slint";
import { Theme } from "./theme.slint";
import { AppConfig } from "./global.slint";
import { MainPage } from "./main.slint";

export { AppConfig }


export component AppWindow inherits Window {
    title: "Querry";
    background: Theme.app_background_color;

    if AppConfig.page == 1 : LandingPage {}
    if AppConfig.page == 2 : MainPage {}

}
