import { Theme } from "./theme.slint";
import { CollectionSection } from "./components/collections.slint";
import { RequestsSection } from "./components/requests.slint";
import { HeadersSection } from "./components/headers.slint";

export component MainPage inherits Rectangle {
    HorizontalLayout {
        CollectionSection {}

        VerticalLayout {
            HeadersSection {}
            RequestsSection {}
        }
    }
}
