export component VerticalSplit inherits Rectangle {
    in-out property <float> proportion: 0.5;

    touch := TouchArea {
        property<bool> on_handle: abs(self.mouse-x - (handle.x)) < 5px;
        mouse-cursor: on_handle ? col-resize : default;

        property<float> new_prop;

        moved => {
            new_prop = root.proportion + (self.mouse-x - self.pressed-x) / root.width;

            if (new_prop >= 0.05 && new_prop <= 0.95 && self.pressed) {
                debug("lalalal: ", new_prop);
                root.proportion = new_prop;
            }
        }
    }

    left := Rectangle {
        width: proportion * parent.width;
    }

    handle := Rectangle {
        x: left.width - handle.width / 2; // Position handle at the right edge of the left panel
        width: 3px;
        height: parent.height;
        background: @linear-gradient(90deg, #ddd, #aaa);
    }

    right := Rectangle {
        width: (1 - proportion) * parent.width;
        x: left.width + handle.width / 2; // Position right side after the handle
    }
}
