export global Theme {
    in-out property <bool> dark_theme: true;

    in-out property<color> app_background_color: dark_theme ? #111214 : #F5F5ED;
    in-out property<color> button_hover_color: #8b4409;
    in-out property<color> button_default_color: #cc5e04;

    in-out property<color> label_text_color: dark_theme ? #fefefe : #101010;
    in-out property<length> label_font_size_small: 9pt;
    in-out property<length> label_font_size_medium_small: 11pt;
    in-out property<length> label_font_size_medium: 14pt;
    in-out property<length> label_font_size_large: 26pt;

    in-out property <length> border_radius: 8px;

    in-out property<color> icon_button_border_color: dark_theme ? #2B2C30 : #D3D3E0;
    in-out property<color> icon_button_image_overlay_color: dark_theme ? #fefefe : #101010;

    in-out property<color> format_toggle_border_color: dark_theme ? #2B2C30 : #D3D3E0;

    in-out property<color> line_color: dark_theme ? #2B2C30 : #D3D3E0;
}
