export global Theme {
    in-out property <bool> dark_theme: false;

    in-out property<color> app_background_color: dark_theme ? #111214 : #F5F5ED;
    in-out property<color> primary_color: #cc5e04;
    in-out property<color> hover_color: primary_color.darker(20%);
    in-out property<length> hover_border_width: 2px;

    in-out property<color> label_text_color: dark_theme ? #fefefe : #101010;
    in-out property<length> label_font_size_small: 10pt;
    in-out property<length> label_font_size_medium_small: 12pt;
    in-out property<length> label_font_size_medium: 17pt;
    in-out property<length> label_font_size_large: 26pt;

    in-out property <length> border_radius: 8px;
    in-out property <float> text_opacity: 0.7;
    in-out property <length> border_width: 1px;
    in-out property <length> icon_width: 25px;
    in-out property <length> icon_width_pressed: 24px;
    in-out property <float> icon_opacity: 0.7;
    in-out property <float> icon_opacity_hover: 0.5;

    in-out property<color> icon_button_border_color: dark_theme ? #2B2C30 : #D3D3E0;
    in-out property<color> icon_button_image_overlay_color: dark_theme ? #fefefe : #101010;

    in-out property<color> border_color: dark_theme ? #2B2C30 : #D3D3E0;
    in-out property<color> icon_color: dark_theme ? #e5e6eb : #1f1f20;
}
